// <auto-generated />
using System;
using FleetManagement.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FleetManagement.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251208153151_WightField")]
    partial class WightField
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FleetManagement.Domain.Aircrafts.Entities.Aircraft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Manufacturer")
                        .HasMaxLength(100)
                        .HasColumnType("integer")
                        .HasColumnName("manufacturer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("registration_number");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("YearOfManufacture")
                        .HasColumnType("integer")
                        .HasColumnName("year_of_manufacture");

                    b.HasKey("Id");

                    b.HasIndex("Manufacturer")
                        .HasDatabaseName("ix_aircrafts_manufacturer");

                    b.HasIndex("Model")
                        .HasDatabaseName("ix_aircrafts_model");

                    b.HasIndex("RegistrationNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_aircrafts_registration_number");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_aircrafts_status");

                    b.ToTable("aircrafts", (string)null);
                });

            modelBuilder.Entity("FleetManagement.Domain.Aircrafts.Entities.AircraftSpecification", b =>
                {
                    b.Property<int>("AircraftId")
                        .HasColumnType("integer");

                    b.Property<string>("BasedStation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("based_station");

                    b.Property<decimal>("MaxLandingWeight")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("max_landing_weight");

                    b.Property<decimal>("MaxTakeoffWeight")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("max_takeoff_weight");

                    b.Property<int>("SeatingCapacity")
                        .HasColumnType("integer")
                        .HasColumnName("seating_capacity");

                    b.Property<int>("WeightUnit")
                        .HasColumnType("integer")
                        .HasColumnName("weight_unit");

                    b.HasKey("AircraftId");

                    b.ToTable("aircraft_specifications", (string)null);
                });

            modelBuilder.Entity("FleetManagement.Domain.Aircrafts.Entities.AircraftSpecification", b =>
                {
                    b.HasOne("FleetManagement.Domain.Aircrafts.Entities.Aircraft", "Aircraft")
                        .WithOne("AircraftSpecification")
                        .HasForeignKey("FleetManagement.Domain.Aircrafts.Entities.AircraftSpecification", "AircraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aircraft");
                });

            modelBuilder.Entity("FleetManagement.Domain.Aircrafts.Entities.Aircraft", b =>
                {
                    b.Navigation("AircraftSpecification")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
