// <auto-generated />
using System;
using FleetManagement.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FleetManagement.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260215160203_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FleetManagement.Domain.Aircrafts.Entities.Aircraft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Manufacturer")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("YearOfManufacture")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Aircrafts");
                });

            modelBuilder.Entity("FleetManagement.Domain.Aircrafts.Entities.AircraftSpecification", b =>
                {
                    b.Property<int>("AircraftId")
                        .HasColumnType("integer");

                    b.Property<string>("BasedStation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("MaxLandingWeight")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MaxTakeoffWeight")
                        .HasColumnType("numeric");

                    b.Property<int>("SeatingCapacity")
                        .HasColumnType("integer");

                    b.Property<int>("WeightUnit")
                        .HasColumnType("integer");

                    b.HasKey("AircraftId");

                    b.ToTable("AircraftSpecification");
                });

            modelBuilder.Entity("FleetManagement.Domain.Components.Entities.AircraftComponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("InstalledDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InstalledOnAircraftId")
                        .HasColumnType("integer");

                    b.Property<int?>("LifeLimitCycles")
                        .HasColumnType("integer");

                    b.Property<int?>("LifeLimitHours")
                        .HasColumnType("integer");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("InstalledOnAircraftId");

                    b.ToTable("AircraftComponent");
                });

            modelBuilder.Entity("FleetManagement.Domain.Maintenance.Entities.MaintenanceEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AircraftId")
                        .HasColumnType("integer");

                    b.Property<int?>("ComponentId")
                        .HasColumnType("integer");

                    b.Property<int?>("ComponentsId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("NextDueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PerformedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AircraftId");

                    b.HasIndex("ComponentsId");

                    b.ToTable("MaintenanceEvent");
                });

            modelBuilder.Entity("FleetManagement.Domain.Aircrafts.Entities.AircraftSpecification", b =>
                {
                    b.HasOne("FleetManagement.Domain.Aircrafts.Entities.Aircraft", "Aircraft")
                        .WithOne("AircraftSpecification")
                        .HasForeignKey("FleetManagement.Domain.Aircrafts.Entities.AircraftSpecification", "AircraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aircraft");
                });

            modelBuilder.Entity("FleetManagement.Domain.Components.Entities.AircraftComponent", b =>
                {
                    b.HasOne("FleetManagement.Domain.Aircrafts.Entities.Aircraft", "InstalledOnAircraft")
                        .WithMany("Component")
                        .HasForeignKey("InstalledOnAircraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InstalledOnAircraft");
                });

            modelBuilder.Entity("FleetManagement.Domain.Maintenance.Entities.MaintenanceEvent", b =>
                {
                    b.HasOne("FleetManagement.Domain.Aircrafts.Entities.Aircraft", "Aircraft")
                        .WithMany("MaintenanceEvents")
                        .HasForeignKey("AircraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FleetManagement.Domain.Components.Entities.AircraftComponent", "Components")
                        .WithMany("MaintenanceEvents")
                        .HasForeignKey("ComponentsId");

                    b.Navigation("Aircraft");

                    b.Navigation("Components");
                });

            modelBuilder.Entity("FleetManagement.Domain.Aircrafts.Entities.Aircraft", b =>
                {
                    b.Navigation("AircraftSpecification")
                        .IsRequired();

                    b.Navigation("Component");

                    b.Navigation("MaintenanceEvents");
                });

            modelBuilder.Entity("FleetManagement.Domain.Components.Entities.AircraftComponent", b =>
                {
                    b.Navigation("MaintenanceEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
